os:
  - linux
  - osx

dist: trusty
sudo: false

language: node_js
node_js:
  - 8
  - 10
  - node

cache:
  directories:
    - "$HOME/.npm"

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export DISPLAY=":99.0";
      sh -e /etc/init.d/xvfb start;
    fi

install:
  # Run `npm install`, if `npm ci` fails, to work around old npm versions' not supporting `npm ci`.
  - npm ci || npm install

script:
  - npm test
